[package]
name = "krust"
version = "0.1.0"
authors = ["Rob Hurkes <rhurkes@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.1.28"
indicatif = "0.11.0"
rdkafka-sys = "1.0.0"
structopt = "0.2.18"

[dependencies.rdkafka]
version = "~0.21"
features = ["dynamic_linking"]
